# .github/workflows/main.yml
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "Hello from self-hosted runner!"
